## Preprocessing

In [ ]:
!pip install keras-tuner

Collecting keras-tuner
  Downloading keras_tuner-1.4.7-py3-none-any.whl (129 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.1/129.1 kB 2.2 MB/s eta 0:00:00
Requirement already satisfied: keras in /usr/local/lib/python3.10/dist-packages (from keras-tuner) (2.15.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from keras-tuner) (23.2)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from keras-tuner) (2.31.0)
Collecting kt-legacy (from keras-tuner)
  Downloading kt_legacy-1.0.5-py3-none-any.whl (9.6 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->keras-tuner) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->keras-tuner) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->keras-tuner) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->keras-tuner) (2024.2.2)
Installing collected packages: kt-legacy, keras-tuner
Successfully installed keras-tuner-1.4.7 kt-legacy-1.0.5

In [ ]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf
import keras_tuner as kt

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [ ]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(columns=['EIN', 'NAME'])

In [ ]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [ ]:
# Look at APPLICATION_TYPE value counts for binning
application_type_value_counts = application_df['APPLICATION_TYPE'].value_counts()
application_type_value_counts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [ ]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(application_type_value_counts[application_type_value_counts<500].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [ ]:
# Look at CLASSIFICATION value counts for binning
classification_value_counts = application_df['CLASSIFICATION'].value_counts()
classification_value_counts

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [ ]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classification_value_counts1 = classification_value_counts[classification_value_counts>1]
classification_value_counts1

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [ ]:
# Choose a cutoff value and create a list of classifications to be replaced
classifications_to_replace = list(classification_value_counts[classification_value_counts <1000].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [ ]:
# Convert categorical data to numeric with `pd.get_dummies`
dummy_df = pd.get_dummies(application_df)
dummy_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [ ]:
# Split our preprocessed data into our features and target arrays
y = dummy_df['IS_SUCCESSFUL']
x = dummy_df.drop(columns='IS_SUCCESSFUL')

# Split the preprocessed data into a training and testing dataset
x_train, x_test, y_train, y_test = train_test_split(x,y, random_state=1, stratify=y)

In [ ]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
x_scaler = scaler.fit(x_train)

# Scale the data
x_train_scaled = x_scaler.transform(x_train)
x_test_scaled = x_scaler.transform(x_test)

## Compile, Train and Evaluate the Model

In [ ]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
input_features = len(x_train_scaled[0])
nn_model = tf.keras.models.Sequential()

# First hidden layer
nn_model.add(tf.keras.layers.Dense(units=80, input_dim = input_features, activation = 'relu'))

# Second hidden layer
nn_model.add(tf.keras.layers.Dense(units=30, activation = 'relu'))

# Output layer
nn_model.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))

# Check the structure of the model
nn_model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 80)                3520

 dense_1 (Dense)             (None, 30)                2430

 dense_2 (Dense)             (None, 1)                 31

=================================================================
Total params: 5981 (23.36 KB)
Trainable params: 5981 (23.36 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [ ]:
# Compile the model
nn_model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [ ]:
# Train the model
nn_model.fit(x_train_scaled, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5710 - accuracy: 0.7167
Epoch 2/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5550 - accuracy: 0.7291
Epoch 3/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5513 - accuracy: 0.7318
Epoch 4/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5492 - accuracy: 0.7321
Epoch 5/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5484 - accuracy: 0.7314
Epoch 6/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5469 - accuracy: 0.7316
Epoch 7/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5468 - accuracy: 0.7325
Epoch 8/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5460 - accuracy: 0.7325
Epoch 9/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5457 - accuracy: 0.7338
Epoch 10/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5448 - accuracy: 0.7324
Epoch 11/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5447 - accuracy: 0.7340
Epoch 12/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5442 - accuracy: 0.7343
Epoch 13/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5444 - accuracy: 0.7341
Epoch 14/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5433 - accuracy: 0.7347
Epoch 15/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5435 - accuracy: 0.7356
Epoch 16/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5429 - accuracy: 0.7350
Epoch 17/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5434 - accuracy: 0.7357
Epoch 18/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5420 - accuracy: 0.7353
Epoch 19/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5423 - accuracy: 0.7348
Epoch 20/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5417 - accuracy: 0.7371
Epoch 21/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5421 - accuracy: 0.7363
Epoch 22/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5414 - accuracy: 0.7358
Epoch 23/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5416 - accuracy: 0.7360
Epoch 24/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5407 - accuracy: 0.7360
Epoch 25/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5405 - accuracy: 0.7359
Epoch 26/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5408 - accuracy: 0.7363
Epoch 27/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5402 - accuracy: 0.7363
Epoch 28/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5404 - accuracy: 0.7368
Epoch 29/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5400 - accuracy: 0.7371
Epoch 30/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5402 - accuracy: 0.7367
Epoch 31/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5395 - accuracy: 0.7375
Epoch 32/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5402 - accuracy: 0.7375
Epoch 33/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5394 - accuracy: 0.7367
Epoch 34/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5395 - accuracy: 0.7373
Epoch 35/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5392 - accuracy: 0.7367
Epoch 36/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5391 - accuracy: 0.7372
Epoch 37/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5384 - accuracy: 0.7381
Epoch 38/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5387 - accuracy: 0.7383
Epoch 39/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5384 - accuracy: 0.7365
Epoch 40/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5381 - accuracy: 0.7381
Epoch 41/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5386 - accuracy: 0.7386
Epoch 42/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5382 - accuracy: 0.7381
Epoch 43/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5384 - accuracy: 0.7376
Epoch 44/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5382 - accuracy: 0.7388
Epoch 45/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5379 - accuracy: 0.7382
Epoch 46/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5376 - accuracy: 0.7385
Epoch 47/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5375 - accuracy: 0.7381
Epoch 48/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5378 - accuracy: 0.7379
Epoch 49/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5377 - accuracy: 0.7378
Epoch 50/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5373 - accuracy: 0.7385

In [ ]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn_model.evaluate(x_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5608 - accuracy: 0.7300 - 882ms/epoch - 3ms/step
Loss: 0.5607646107673645, Accuracy: 0.7300291657447815

In [ ]:
nn_model.save('AlphabetSoupCharity.h5')

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(